import QtQuick 2.0

ListModel{
    // IconsLists
    ListElement{ name:"icon3d_rotation"; value:"\ue84d"}
    ListElement{ name:"ac_unit"; value:"\ueb3b"}
    ListElement{ name:"access_alarm"; value:"\ue190"}
    ListElement{ name:"access_alarms"; value:"\ue191"}
    ListElement{ name:"access_time"; value:"\ue192"}
    ListElement{ name:"accessibility"; value:"\ue84e"}
    ListElement{ name:"accessible"; value:"\ue914"}
    ListElement{ name:"account_balance"; value:"\ue84f"}
    ListElement{ name:"account_balance_wallet"; value:"\ue850"}
    ListElement{ name:"account_box"; value:"\ue851"}
    ListElement{ name:"account_circle"; value:"\ue853"}
    ListElement{ name:"adb"; value:"\ue60e"}
    ListElement{ name:"add"; value:"\ue145"}
    ListElement{ name:"add_a_photo"; value:"\ue439"}
    ListElement{ name:"add_alarm"; value:"\ue193"}
    ListElement{ name:"add_alert"; value:"\ue003"}
    ListElement{ name:"add_box"; value:"\ue146"}
    ListElement{ name:"add_circle"; value:"\ue147"}
    ListElement{ name:"add_circle_outline"; value:"\ue148"}
    ListElement{ name:"add_location"; value:"\ue567"}
    ListElement{ name:"add_shopping_cart"; value:"\ue854"}
    ListElement{ name:"add_to_photos"; value:"\ue39d"}
    ListElement{ name:"add_to_queue"; value:"\ue05c"}
    ListElement{ name:"adjust"; value:"\ue39e"}
    ListElement{ name:"airline_seat_flat"; value:"\ue630"}
    ListElement{ name:"airline_seat_flat_angled"; value:"\ue631"}
    ListElement{ name:"airline_seat_individual_suite"; value:"\ue632"}
    ListElement{ name:"airline_seat_legroom_extra"; value:"\ue633"}
    ListElement{ name:"airline_seat_legroom_normal"; value:"\ue634"}
    ListElement{ name:"airline_seat_legroom_reduced"; value:"\ue635"}
    ListElement{ name:"airline_seat_recline_extra"; value:"\ue636"}
    ListElement{ name:"airline_seat_recline_normal"; value:"\ue637"}
    ListElement{ name:"airplanemode_active"; value:"\ue195"}
    ListElement{ name:"airplanemode_inactive"; value:"\ue194"}
    ListElement{ name:"airplay"; value:"\ue055"}
    ListElement{ name:"airport_shuttle"; value:"\ueb3c"}
    ListElement{ name:"alarm"; value:"\ue855"}
    ListElement{ name:"alarm_add"; value:"\ue856"}
    ListElement{ name:"alarm_off"; value:"\ue857"}
    ListElement{ name:"alarm_on"; value:"\ue858"}
    ListElement{ name:"album"; value:"\ue019"}
    ListElement{ name:"all_inclusive"; value:"\ueb3d"}
    ListElement{ name:"all_out"; value:"\ue90b"}
    ListElement{ name:"android"; value:"\ue859"}
    ListElement{ name:"announcement"; value:"\ue85a"}
    ListElement{ name:"apps"; value:"\ue5c3"}
    ListElement{ name:"archive"; value:"\ue149"}
    ListElement{ name:"arrow_back"; value:"\ue5c4"}
    ListElement{ name:"arrow_downward"; value:"\ue5db"}
    ListElement{ name:"arrow_drop_down"; value:"\ue5c5"}
    ListElement{ name:"arrow_drop_down_circle"; value:"\ue5c6"}
    ListElement{ name:"arrow_drop_up"; value:"\ue5c7"}
    ListElement{ name:"arrow_forward"; value:"\ue5c8"}
    ListElement{ name:"arrow_upward"; value:"\ue5d8"}
    ListElement{ name:"art_track"; value:"\ue060"}
    ListElement{ name:"aspect_ratio"; value:"\ue85b"}
    ListElement{ name:"assessment"; value:"\ue85c"}
    ListElement{ name:"assignment"; value:"\ue85d"}
    ListElement{ name:"assignment_ind"; value:"\ue85e"}
    ListElement{ name:"assignment_late"; value:"\ue85f"}
    ListElement{ name:"assignment_return"; value:"\ue860"}
    ListElement{ name:"assignment_returned"; value:"\ue861"}
    ListElement{ name:"assignment_turned_in"; value:"\ue862"}
    ListElement{ name:"assistant"; value:"\ue39f"}
    ListElement{ name:"assistant_photo"; value:"\ue3a0"}
    ListElement{ name:"attach_file"; value:"\ue226"}
    ListElement{ name:"attach_money"; value:"\ue227"}
    ListElement{ name:"attachment"; value:"\ue2bc"}
    ListElement{ name:"audiotrack"; value:"\ue3a1"}
    ListElement{ name:"autorenew"; value:"\ue863"}
    ListElement{ name:"av_timer"; value:"\ue01b"}
    ListElement{ name:"backspace"; value:"\ue14a"}
    ListElement{ name:"backup"; value:"\ue864"}
    ListElement{ name:"battery_alert"; value:"\ue19c"}
    ListElement{ name:"battery_charging_full"; value:"\ue1a3"}
    ListElement{ name:"battery_full"; value:"\ue1a4"}
    ListElement{ name:"battery_std"; value:"\ue1a5"}
    ListElement{ name:"battery_unknown"; value:"\ue1a6"}
    ListElement{ name:"beach_access"; value:"\ueb3e"}
    ListElement{ name:"beenhere"; value:"\ue52d"}
    ListElement{ name:"block"; value:"\ue14b"}
    ListElement{ name:"bluetooth"; value:"\ue1a7"}
    ListElement{ name:"bluetooth_audio"; value:"\ue60f"}
    ListElement{ name:"bluetooth_connected"; value:"\ue1a8"}
    ListElement{ name:"bluetooth_disabled"; value:"\ue1a9"}
    ListElement{ name:"bluetooth_searching"; value:"\ue1aa"}
    ListElement{ name:"blur_circular"; value:"\ue3a2"}
    ListElement{ name:"blur_linear"; value:"\ue3a3"}
    ListElement{ name:"blur_off"; value:"\ue3a4"}
    ListElement{ name:"blur_on"; value:"\ue3a5"}
    ListElement{ name:"book"; value:"\ue865"}
    ListElement{ name:"bookmark"; value:"\ue866"}
    ListElement{ name:"bookmark_border"; value:"\ue867"}
    ListElement{ name:"border_all"; value:"\ue228"}
    ListElement{ name:"border_bottom"; value:"\ue229"}
    ListElement{ name:"border_clear"; value:"\ue22a"}
    ListElement{ name:"border_color"; value:"\ue22b"}
    ListElement{ name:"border_horizontal"; value:"\ue22c"}
    ListElement{ name:"border_inner"; value:"\ue22d"}
    ListElement{ name:"border_left"; value:"\ue22e"}
    ListElement{ name:"border_outer"; value:"\ue22f"}
    ListElement{ name:"border_right"; value:"\ue230"}
    ListElement{ name:"border_style"; value:"\ue231"}
    ListElement{ name:"border_top"; value:"\ue232"}
    ListElement{ name:"border_vertical"; value:"\ue233"}
    ListElement{ name:"branding_watermark"; value:"\ue06b"}
    ListElement{ name:"brightness_1"; value:"\ue3a6"}
    ListElement{ name:"brightness_2"; value:"\ue3a7"}
    ListElement{ name:"brightness_3"; value:"\ue3a8"}
    ListElement{ name:"brightness_4"; value:"\ue3a9"}
    ListElement{ name:"brightness_5"; value:"\ue3aa"}
    ListElement{ name:"brightness_6"; value:"\ue3ab"}
    ListElement{ name:"brightness_7"; value:"\ue3ac"}
    ListElement{ name:"brightness_auto"; value:"\ue1ab"}
    ListElement{ name:"brightness_high"; value:"\ue1ac"}
    ListElement{ name:"brightness_low"; value:"\ue1ad"}
    ListElement{ name:"brightness_medium"; value:"\ue1ae"}
    ListElement{ name:"broken_image"; value:"\ue3ad"}
    ListElement{ name:"brush"; value:"\ue3ae"}
    ListElement{ name:"bubble_chart"; value:"\ue6dd"}
    ListElement{ name:"bug_report"; value:"\ue868"}
    ListElement{ name:"build"; value:"\ue869"}
    ListElement{ name:"burst_mode"; value:"\ue43c"}
    ListElement{ name:"business"; value:"\ue0af"}
    ListElement{ name:"business_center"; value:"\ueb3f"}
    ListElement{ name:"cached"; value:"\ue86a"}
    ListElement{ name:"cake"; value:"\ue7e9"}
    ListElement{ name:"call"; value:"\ue0b0"}
    ListElement{ name:"call_end"; value:"\ue0b1"}
    ListElement{ name:"call_made"; value:"\ue0b2"}
    ListElement{ name:"call_merge"; value:"\ue0b3"}
    ListElement{ name:"call_missed"; value:"\ue0b4"}
    ListElement{ name:"call_missed_outgoing"; value:"\ue0e4"}
    ListElement{ name:"call_received"; value:"\ue0b5"}
    ListElement{ name:"call_split"; value:"\ue0b6"}
    ListElement{ name:"call_to_action"; value:"\ue06c"}
    ListElement{ name:"camera"; value:"\ue3af"}
    ListElement{ name:"camera_alt"; value:"\ue3b0"}
    ListElement{ name:"camera_enhance"; value:"\ue8fc"}
    ListElement{ name:"camera_front"; value:"\ue3b1"}
    ListElement{ name:"camera_rear"; value:"\ue3b2"}
    ListElement{ name:"camera_roll"; value:"\ue3b3"}
    ListElement{ name:"cancel"; value:"\ue5c9"}
    ListElement{ name:"card_giftcard"; value:"\ue8f6"}
    ListElement{ name:"card_membership"; value:"\ue8f7"}
    ListElement{ name:"card_travel"; value:"\ue8f8"}
    ListElement{ name:"casino"; value:"\ueb40"}
    ListElement{ name:"cast"; value:"\ue307"}
    ListElement{ name:"cast_connected"; value:"\ue308"}
    ListElement{ name:"center_focus_strong"; value:"\ue3b4"}
    ListElement{ name:"center_focus_weak"; value:"\ue3b5"}
    ListElement{ name:"change_history"; value:"\ue86b"}
    ListElement{ name:"chat"; value:"\ue0b7"}
    ListElement{ name:"chat_bubble"; value:"\ue0ca"}
    ListElement{ name:"chat_bubble_outline"; value:"\ue0cb"}
    ListElement{ name:"check"; value:"\ue5ca"}
    ListElement{ name:"check_box"; value:"\ue834"}
    ListElement{ name:"check_box_outline_blank"; value:"\ue835"}
    ListElement{ name:"check_circle"; value:"\ue86c"}
    ListElement{ name:"chevron_left"; value:"\ue5cb"}
    ListElement{ name:"chevron_right"; value:"\ue5cc"}
    ListElement{ name:"child_care"; value:"\ueb41"}
    ListElement{ name:"child_friendly"; value:"\ueb42"}
    ListElement{ name:"chrome_reader_mode"; value:"\ue86d"}
    ListElement{ name:"iconclass"; value:"\ue86e"}
    ListElement{ name:"clear"; value:"\ue14c"}
    ListElement{ name:"clear_all"; value:"\ue0b8"}
    ListElement{ name:"close"; value:"\ue5cd"}
    ListElement{ name:"closed_caption"; value:"\ue01c"}
    ListElement{ name:"cloud"; value:"\ue2bd"}
    ListElement{ name:"cloud_circle"; value:"\ue2be"}
    ListElement{ name:"cloud_done"; value:"\ue2bf"}
    ListElement{ name:"cloud_download"; value:"\ue2c0"}
    ListElement{ name:"cloud_off"; value:"\ue2c1"}
    ListElement{ name:"cloud_queue"; value:"\ue2c2"}
    ListElement{ name:"cloud_upload"; value:"\ue2c3"}
    ListElement{ name:"code"; value:"\ue86f"}
    ListElement{ name:"collections"; value:"\ue3b6"}
    ListElement{ name:"collections_bookmark"; value:"\ue431"}
    ListElement{ name:"color_lens"; value:"\ue3b7"}
    ListElement{ name:"colorize"; value:"\ue3b8"}
    ListElement{ name:"comment"; value:"\ue0b9"}
    ListElement{ name:"compare"; value:"\ue3b9"}
    ListElement{ name:"compare_arrows"; value:"\ue915"}
    ListElement{ name:"computer"; value:"\ue30a"}
    ListElement{ name:"confirmation_number"; value:"\ue638"}
    ListElement{ name:"contact_mail"; value:"\ue0d0"}
    ListElement{ name:"contact_phone"; value:"\ue0cf"}
    ListElement{ name:"contacts"; value:"\ue0ba"}
    ListElement{ name:"content_copy"; value:"\ue14d"}
    ListElement{ name:"content_cut"; value:"\ue14e"}
    ListElement{ name:"content_paste"; value:"\ue14f"}
    ListElement{ name:"control_point"; value:"\ue3ba"}
    ListElement{ name:"control_point_duplicate"; value:"\ue3bb"}
    ListElement{ name:"copyright"; value:"\ue90c"}
    ListElement{ name:"create"; value:"\ue150"}
    ListElement{ name:"create_new_folder"; value:"\ue2cc"}
    ListElement{ name:"credit_card"; value:"\ue870"}
    ListElement{ name:"crop"; value:"\ue3be"}
    ListElement{ name:"crop_16_9"; value:"\ue3bc"}
    ListElement{ name:"crop_3_2"; value:"\ue3bd"}
    ListElement{ name:"crop_5_4"; value:"\ue3bf"}
    ListElement{ name:"crop_7_5"; value:"\ue3c0"}
    ListElement{ name:"crop_din"; value:"\ue3c1"}
    ListElement{ name:"crop_free"; value:"\ue3c2"}
    ListElement{ name:"crop_landscape"; value:"\ue3c3"}
    ListElement{ name:"crop_original"; value:"\ue3c4"}
    ListElement{ name:"crop_portrait"; value:"\ue3c5"}
    ListElement{ name:"crop_rotate"; value:"\ue437"}
    ListElement{ name:"crop_square"; value:"\ue3c6"}
    ListElement{ name:"dashboard"; value:"\ue871"}
    ListElement{ name:"data_usage"; value:"\ue1af"}
    ListElement{ name:"date_range"; value:"\ue916"}
    ListElement{ name:"dehaze"; value:"\ue3c7"}
    ListElement{ name:"icondelete"; value:"\ue872"}
    ListElement{ name:"delete_forever"; value:"\ue92b"}
    ListElement{ name:"delete_sweep"; value:"\ue16c"}
    ListElement{ name:"description"; value:"\ue873"}
    ListElement{ name:"desktop_mac"; value:"\ue30b"}
    ListElement{ name:"desktop_windows"; value:"\ue30c"}
    ListElement{ name:"details"; value:"\ue3c8"}
    ListElement{ name:"developer_board"; value:"\ue30d"}
    ListElement{ name:"developer_mode"; value:"\ue1b0"}
    ListElement{ name:"device_hub"; value:"\ue335"}
    ListElement{ name:"devices"; value:"\ue1b1"}
    ListElement{ name:"devices_other"; value:"\ue337"}
    ListElement{ name:"dialer_sip"; value:"\ue0bb"}
    ListElement{ name:"dialpad"; value:"\ue0bc"}
    ListElement{ name:"directions"; value:"\ue52e"}
    ListElement{ name:"directions_bike"; value:"\ue52f"}
    ListElement{ name:"directions_boat"; value:"\ue532"}
    ListElement{ name:"directions_bus"; value:"\ue530"}
    ListElement{ name:"directions_car"; value:"\ue531"}
    ListElement{ name:"directions_railway"; value:"\ue534"}
    ListElement{ name:"directions_run"; value:"\ue566"}
    ListElement{ name:"directions_subway"; value:"\ue533"}
    ListElement{ name:"directions_transit"; value:"\ue535"}
    ListElement{ name:"directions_walk"; value:"\ue536"}
    ListElement{ name:"disc_full"; value:"\ue610"}
    ListElement{ name:"dns"; value:"\ue875"}
    ListElement{ name:"do_not_disturb"; value:"\ue612"}
    ListElement{ name:"do_not_disturb_alt"; value:"\ue611"}
    ListElement{ name:"do_not_disturb_off"; value:"\ue643"}
    ListElement{ name:"do_not_disturb_on"; value:"\ue644"}
    ListElement{ name:"dock"; value:"\ue30e"}
    ListElement{ name:"domain"; value:"\ue7ee"}
    ListElement{ name:"done"; value:"\ue876"}
    ListElement{ name:"done_all"; value:"\ue877"}
    ListElement{ name:"donut_large"; value:"\ue917"}
    ListElement{ name:"donut_small"; value:"\ue918"}
    ListElement{ name:"drafts"; value:"\ue151"}
    ListElement{ name:"drag_handle"; value:"\ue25d"}
    ListElement{ name:"drive_eta"; value:"\ue613"}
    ListElement{ name:"dvr"; value:"\ue1b2"}
    ListElement{ name:"edit"; value:"\ue3c9"}
    ListElement{ name:"edit_location"; value:"\ue568"}
    ListElement{ name:"eject"; value:"\ue8fb"}
    ListElement{ name:"email"; value:"\ue0be"}
    ListElement{ name:"enhanced_encryption"; value:"\ue63f"}
    ListElement{ name:"equalizer"; value:"\ue01d"}
    ListElement{ name:"error"; value:"\ue000"}
    ListElement{ name:"error_outline"; value:"\ue001"}
    ListElement{ name:"euro_symbol"; value:"\ue926"}
    ListElement{ name:"ev_station"; value:"\ue56d"}
    ListElement{ name:"event"; value:"\ue878"}
    ListElement{ name:"event_available"; value:"\ue614"}
    ListElement{ name:"event_busy"; value:"\ue615"}
    ListElement{ name:"event_note"; value:"\ue616"}
    ListElement{ name:"event_seat"; value:"\ue903"}
    ListElement{ name:"exit_to_app"; value:"\ue879"}
    ListElement{ name:"expand_less"; value:"\ue5ce"}
    ListElement{ name:"expand_more"; value:"\ue5cf"}
    ListElement{ name:"explicit"; value:"\ue01e"}
    ListElement{ name:"explore"; value:"\ue87a"}
    ListElement{ name:"exposure"; value:"\ue3ca"}
    ListElement{ name:"exposure_neg_1"; value:"\ue3cb"}
    ListElement{ name:"exposure_neg_2"; value:"\ue3cc"}
    ListElement{ name:"exposure_plus_1"; value:"\ue3cd"}
    ListElement{ name:"exposure_plus_2"; value:"\ue3ce"}
    ListElement{ name:"exposure_zero"; value:"\ue3cf"}
    ListElement{ name:"extension"; value:"\ue87b"}
    ListElement{ name:"face"; value:"\ue87c"}
    ListElement{ name:"fast_forward"; value:"\ue01f"}
    ListElement{ name:"fast_rewind"; value:"\ue020"}
    ListElement{ name:"favorite"; value:"\ue87d"}
    ListElement{ name:"favorite_border"; value:"\ue87e"}
    ListElement{ name:"featured_play_list"; value:"\ue06d"}
    ListElement{ name:"featured_video"; value:"\ue06e"}
    ListElement{ name:"feedback"; value:"\ue87f"}
    ListElement{ name:"fiber_dvr"; value:"\ue05d"}
    ListElement{ name:"fiber_manual_record"; value:"\ue061"}
    ListElement{ name:"fiber_new"; value:"\ue05e"}
    ListElement{ name:"fiber_pin"; value:"\ue06a"}
    ListElement{ name:"fiber_smart_record"; value:"\ue062"}
    ListElement{ name:"file_download"; value:"\ue2c4"}
    ListElement{ name:"file_upload"; value:"\ue2c6"}
    ListElement{ name:"filter"; value:"\ue3d3"}
    ListElement{ name:"filter_1"; value:"\ue3d0"}
    ListElement{ name:"filter_2"; value:"\ue3d1"}
    ListElement{ name:"filter_3"; value:"\ue3d2"}
    ListElement{ name:"filter_4"; value:"\ue3d4"}
    ListElement{ name:"filter_5"; value:"\ue3d5"}
    ListElement{ name:"filter_6"; value:"\ue3d6"}
    ListElement{ name:"filter_7"; value:"\ue3d7"}
    ListElement{ name:"filter_8"; value:"\ue3d8"}
    ListElement{ name:"filter_9"; value:"\ue3d9"}
    ListElement{ name:"filter_9_plus"; value:"\ue3da"}
    ListElement{ name:"filter_b_and_w"; value:"\ue3db"}
    ListElement{ name:"filter_center_focus"; value:"\ue3dc"}
    ListElement{ name:"filter_drama"; value:"\ue3dd"}
    ListElement{ name:"filter_frames"; value:"\ue3de"}
    ListElement{ name:"filter_hdr"; value:"\ue3df"}
    ListElement{ name:"filter_list"; value:"\ue152"}
    ListElement{ name:"filter_none"; value:"\ue3e0"}
    ListElement{ name:"filter_tilt_shift"; value:"\ue3e2"}
    ListElement{ name:"filter_vintage"; value:"\ue3e3"}
    ListElement{ name:"find_in_page"; value:"\ue880"}
    ListElement{ name:"find_replace"; value:"\ue881"}
    ListElement{ name:"fingerprint"; value:"\ue90d"}
    ListElement{ name:"first_page"; value:"\ue5dc"}
    ListElement{ name:"fitness_center"; value:"\ueb43"}
    ListElement{ name:"flag"; value:"\ue153"}
    ListElement{ name:"flare"; value:"\ue3e4"}
    ListElement{ name:"flash_auto"; value:"\ue3e5"}
    ListElement{ name:"flash_off"; value:"\ue3e6"}
    ListElement{ name:"flash_on"; value:"\ue3e7"}
    ListElement{ name:"flight"; value:"\ue539"}
    ListElement{ name:"flight_land"; value:"\ue904"}
    ListElement{ name:"flight_takeoff"; value:"\ue905"}
    ListElement{ name:"flip"; value:"\ue3e8"}
    ListElement{ name:"flip_to_back"; value:"\ue882"}
    ListElement{ name:"flip_to_front"; value:"\ue883"}
    ListElement{ name:"folder"; value:"\ue2c7"}
    ListElement{ name:"folder_open"; value:"\ue2c8"}
    ListElement{ name:"folder_shared"; value:"\ue2c9"}
    ListElement{ name:"folder_special"; value:"\ue617"}
    ListElement{ name:"font_download"; value:"\ue167"}
    ListElement{ name:"format_align_center"; value:"\ue234"}
    ListElement{ name:"format_align_justify"; value:"\ue235"}
    ListElement{ name:"format_align_left"; value:"\ue236"}
    ListElement{ name:"format_align_right"; value:"\ue237"}
    ListElement{ name:"format_bold"; value:"\ue238"}
    ListElement{ name:"format_clear"; value:"\ue239"}
    ListElement{ name:"format_color_fill"; value:"\ue23a"}
    ListElement{ name:"format_color_reset"; value:"\ue23b"}
    ListElement{ name:"format_color_text"; value:"\ue23c"}
    ListElement{ name:"format_indent_decrease"; value:"\ue23d"}
    ListElement{ name:"format_indent_increase"; value:"\ue23e"}
    ListElement{ name:"format_italic"; value:"\ue23f"}
    ListElement{ name:"format_line_spacing"; value:"\ue240"}
    ListElement{ name:"format_list_bulleted"; value:"\ue241"}
    ListElement{ name:"format_list_numbered"; value:"\ue242"}
    ListElement{ name:"format_paint"; value:"\ue243"}
    ListElement{ name:"format_quote"; value:"\ue244"}
    ListElement{ name:"format_shapes"; value:"\ue25e"}
    ListElement{ name:"format_size"; value:"\ue245"}
    ListElement{ name:"format_strikethrough"; value:"\ue246"}
    ListElement{ name:"format_textdirection_l_to_r"; value:"\ue247"}
    ListElement{ name:"format_textdirection_r_to_l"; value:"\ue248"}
    ListElement{ name:"format_underlined"; value:"\ue249"}
    ListElement{ name:"forum"; value:"\ue0bf"}
    ListElement{ name:"forward"; value:"\ue154"}
    ListElement{ name:"forward_10"; value:"\ue056"}
    ListElement{ name:"forward_30"; value:"\ue057"}
    ListElement{ name:"forward_5"; value:"\ue058"}
    ListElement{ name:"free_breakfast"; value:"\ueb44"}
    ListElement{ name:"fullscreen"; value:"\ue5d0"}
    ListElement{ name:"fullscreen_exit"; value:"\ue5d1"}
    ListElement{ name:"functions"; value:"\ue24a"}
    ListElement{ name:"g_translate"; value:"\ue927"}
    ListElement{ name:"gamepad"; value:"\ue30f"}
    ListElement{ name:"games"; value:"\ue021"}
    ListElement{ name:"gavel"; value:"\ue90e"}
    ListElement{ name:"gesture"; value:"\ue155"}
    ListElement{ name:"get_app"; value:"\ue884"}
    ListElement{ name:"gif"; value:"\ue908"}
    ListElement{ name:"golf_course"; value:"\ueb45"}
    ListElement{ name:"gps_fixed"; value:"\ue1b3"}
    ListElement{ name:"gps_not_fixed"; value:"\ue1b4"}
    ListElement{ name:"gps_off"; value:"\ue1b5"}
    ListElement{ name:"grade"; value:"\ue885"}
    ListElement{ name:"gradient"; value:"\ue3e9"}
    ListElement{ name:"grain"; value:"\ue3ea"}
    ListElement{ name:"graphic_eq"; value:"\ue1b8"}
    ListElement{ name:"grid_off"; value:"\ue3eb"}
    ListElement{ name:"grid_on"; value:"\ue3ec"}
    ListElement{ name:"group"; value:"\ue7ef"}
    ListElement{ name:"group_add"; value:"\ue7f0"}
    ListElement{ name:"group_work"; value:"\ue886"}
    ListElement{ name:"hd"; value:"\ue052"}
    ListElement{ name:"hdr_off"; value:"\ue3ed"}
    ListElement{ name:"hdr_on"; value:"\ue3ee"}
    ListElement{ name:"hdr_strong"; value:"\ue3f1"}
    ListElement{ name:"hdr_weak"; value:"\ue3f2"}
    ListElement{ name:"headset"; value:"\ue310"}
    ListElement{ name:"headset_mic"; value:"\ue311"}
    ListElement{ name:"healing"; value:"\ue3f3"}
    ListElement{ name:"hearing"; value:"\ue023"}
    ListElement{ name:"help"; value:"\ue887"}
    ListElement{ name:"help_outline"; value:"\ue8fd"}
    ListElement{ name:"high_quality"; value:"\ue024"}
    ListElement{ name:"highlight"; value:"\ue25f"}
    ListElement{ name:"highlight_off"; value:"\ue888"}
    ListElement{ name:"history"; value:"\ue889"}
    ListElement{ name:"home"; value:"\ue88a"}
    ListElement{ name:"hot_tub"; value:"\ueb46"}
    ListElement{ name:"hotel"; value:"\ue53a"}
    ListElement{ name:"hourglass_empty"; value:"\ue88b"}
    ListElement{ name:"hourglass_full"; value:"\ue88c"}
    ListElement{ name:"http"; value:"\ue902"}
    ListElement{ name:"https"; value:"\ue88d"}
    ListElement{ name:"image"; value:"\ue3f4"}
    ListElement{ name:"image_aspect_ratio"; value:"\ue3f5"}
    ListElement{ name:"import_contacts"; value:"\ue0e0"}
    ListElement{ name:"import_export"; value:"\ue0c3"}
    ListElement{ name:"important_devices"; value:"\ue912"}
    ListElement{ name:"inbox"; value:"\ue156"}
    ListElement{ name:"indeterminate_check_box"; value:"\ue909"}
    ListElement{ name:"info"; value:"\ue88e"}
    ListElement{ name:"info_outline"; value:"\ue88f"}
    ListElement{ name:"input"; value:"\ue890"}
    ListElement{ name:"insert_chart"; value:"\ue24b"}
    ListElement{ name:"insert_comment"; value:"\ue24c"}
    ListElement{ name:"insert_drive_file"; value:"\ue24d"}
    ListElement{ name:"insert_emoticon"; value:"\ue24e"}
    ListElement{ name:"insert_invitation"; value:"\ue24f"}
    ListElement{ name:"insert_link"; value:"\ue250"}
    ListElement{ name:"insert_photo"; value:"\ue251"}
    ListElement{ name:"invert_colors"; value:"\ue891"}
    ListElement{ name:"invert_colors_off"; value:"\ue0c4"}
    ListElement{ name:"iso"; value:"\ue3f6"}
    ListElement{ name:"keyboard"; value:"\ue312"}
    ListElement{ name:"keyboard_arrow_down"; value:"\ue313"}
    ListElement{ name:"keyboard_arrow_left"; value:"\ue314"}
    ListElement{ name:"keyboard_arrow_right"; value:"\ue315"}
    ListElement{ name:"keyboard_arrow_up"; value:"\ue316"}
    ListElement{ name:"keyboard_backspace"; value:"\ue317"}
    ListElement{ name:"keyboard_capslock"; value:"\ue318"}
    ListElement{ name:"keyboard_hide"; value:"\ue31a"}
    ListElement{ name:"keyboard_return"; value:"\ue31b"}
    ListElement{ name:"keyboard_tab"; value:"\ue31c"}
    ListElement{ name:"keyboard_voice"; value:"\ue31d"}
    ListElement{ name:"kitchen"; value:"\ueb47"}
    ListElement{ name:"label"; value:"\ue892"}
    ListElement{ name:"label_outline"; value:"\ue893"}
    ListElement{ name:"landscape"; value:"\ue3f7"}
    ListElement{ name:"language"; value:"\ue894"}
    ListElement{ name:"laptop"; value:"\ue31e"}
    ListElement{ name:"laptop_chromebook"; value:"\ue31f"}
    ListElement{ name:"laptop_mac"; value:"\ue320"}
    ListElement{ name:"laptop_windows"; value:"\ue321"}
    ListElement{ name:"last_page"; value:"\ue5dd"}
    ListElement{ name:"launch"; value:"\ue895"}
    ListElement{ name:"layers"; value:"\ue53b"}
    ListElement{ name:"layers_clear"; value:"\ue53c"}
    ListElement{ name:"leak_add"; value:"\ue3f8"}
    ListElement{ name:"leak_remove"; value:"\ue3f9"}
    ListElement{ name:"lens"; value:"\ue3fa"}
    ListElement{ name:"library_add"; value:"\ue02e"}
    ListElement{ name:"library_books"; value:"\ue02f"}
    ListElement{ name:"library_music"; value:"\ue030"}
    ListElement{ name:"lightbulb_outline"; value:"\ue90f"}
    ListElement{ name:"line_style"; value:"\ue919"}
    ListElement{ name:"line_weight"; value:"\ue91a"}
    ListElement{ name:"linear_scale"; value:"\ue260"}
    ListElement{ name:"link"; value:"\ue157"}
    ListElement{ name:"linked_camera"; value:"\ue438"}
    ListElement{ name:"list"; value:"\ue896"}
    ListElement{ name:"live_help"; value:"\ue0c6"}
    ListElement{ name:"live_tv"; value:"\ue639"}
    ListElement{ name:"local_activity"; value:"\ue53f"}
    ListElement{ name:"local_airport"; value:"\ue53d"}
    ListElement{ name:"local_atm"; value:"\ue53e"}
    ListElement{ name:"local_bar"; value:"\ue540"}
    ListElement{ name:"local_cafe"; value:"\ue541"}
    ListElement{ name:"local_car_wash"; value:"\ue542"}
    ListElement{ name:"local_convenience_store"; value:"\ue543"}
    ListElement{ name:"local_dining"; value:"\ue556"}
    ListElement{ name:"local_drink"; value:"\ue544"}
    ListElement{ name:"local_florist"; value:"\ue545"}
    ListElement{ name:"local_gas_station"; value:"\ue546"}
    ListElement{ name:"local_grocery_store"; value:"\ue547"}
    ListElement{ name:"local_hospital"; value:"\ue548"}
    ListElement{ name:"local_hotel"; value:"\ue549"}
    ListElement{ name:"local_laundry_service"; value:"\ue54a"}
    ListElement{ name:"local_library"; value:"\ue54b"}
    ListElement{ name:"local_mall"; value:"\ue54c"}
    ListElement{ name:"local_movies"; value:"\ue54d"}
    ListElement{ name:"local_offer"; value:"\ue54e"}
    ListElement{ name:"local_parking"; value:"\ue54f"}
    ListElement{ name:"local_pharmacy"; value:"\ue550"}
    ListElement{ name:"local_phone"; value:"\ue551"}
    ListElement{ name:"local_pizza"; value:"\ue552"}
    ListElement{ name:"local_play"; value:"\ue553"}
    ListElement{ name:"local_post_office"; value:"\ue554"}
    ListElement{ name:"local_printshop"; value:"\ue555"}
    ListElement{ name:"local_see"; value:"\ue557"}
    ListElement{ name:"local_shipping"; value:"\ue558"}
    ListElement{ name:"local_taxi"; value:"\ue559"}
    ListElement{ name:"location_city"; value:"\ue7f1"}
    ListElement{ name:"location_disabled"; value:"\ue1b6"}
    ListElement{ name:"location_off"; value:"\ue0c7"}
    ListElement{ name:"location_on"; value:"\ue0c8"}
    ListElement{ name:"location_searching"; value:"\ue1b7"}
    ListElement{ name:"lock"; value:"\ue897"}
    ListElement{ name:"lock_open"; value:"\ue898"}
    ListElement{ name:"lock_outline"; value:"\ue899"}
    ListElement{ name:"looks"; value:"\ue3fc"}
    ListElement{ name:"looks_3"; value:"\ue3fb"}
    ListElement{ name:"looks_4"; value:"\ue3fd"}
    ListElement{ name:"looks_5"; value:"\ue3fe"}
    ListElement{ name:"looks_6"; value:"\ue3ff"}
    ListElement{ name:"looks_one"; value:"\ue400"}
    ListElement{ name:"looks_two"; value:"\ue401"}
    ListElement{ name:"loop"; value:"\ue028"}
    ListElement{ name:"loupe"; value:"\ue402"}
    ListElement{ name:"low_priority"; value:"\ue16d"}
    ListElement{ name:"loyalty"; value:"\ue89a"}
    ListElement{ name:"mail"; value:"\ue158"}
    ListElement{ name:"mail_outline"; value:"\ue0e1"}
    ListElement{ name:"map"; value:"\ue55b"}
    ListElement{ name:"markunread"; value:"\ue159"}
    ListElement{ name:"markunread_mailbox"; value:"\ue89b"}
    ListElement{ name:"memory"; value:"\ue322"}
    ListElement{ name:"menu"; value:"\ue5d2"}
    ListElement{ name:"merge_type"; value:"\ue252"}
    ListElement{ name:"message"; value:"\ue0c9"}
    ListElement{ name:"mic"; value:"\ue029"}
    ListElement{ name:"mic_none"; value:"\ue02a"}
    ListElement{ name:"mic_off"; value:"\ue02b"}
    ListElement{ name:"mms"; value:"\ue618"}
    ListElement{ name:"mode_comment"; value:"\ue253"}
    ListElement{ name:"mode_edit"; value:"\ue254"}
    ListElement{ name:"monetization_on"; value:"\ue263"}
    ListElement{ name:"money_off"; value:"\ue25c"}
    ListElement{ name:"monochrome_photos"; value:"\ue403"}
    ListElement{ name:"mood"; value:"\ue7f2"}
    ListElement{ name:"mood_bad"; value:"\ue7f3"}
    ListElement{ name:"more"; value:"\ue619"}
    ListElement{ name:"more_horiz"; value:"\ue5d3"}
    ListElement{ name:"more_vert"; value:"\ue5d4"}
    ListElement{ name:"motorcycle"; value:"\ue91b"}
    ListElement{ name:"mouse"; value:"\ue323"}
    ListElement{ name:"move_to_inbox"; value:"\ue168"}
    ListElement{ name:"movie"; value:"\ue02c"}
    ListElement{ name:"movie_creation"; value:"\ue404"}
    ListElement{ name:"movie_filter"; value:"\ue43a"}
    ListElement{ name:"multiline_chart"; value:"\ue6df"}
    ListElement{ name:"music_note"; value:"\ue405"}
    ListElement{ name:"music_video"; value:"\ue063"}
    ListElement{ name:"my_location"; value:"\ue55c"}
    ListElement{ name:"nature"; value:"\ue406"}
    ListElement{ name:"nature_people"; value:"\ue407"}
    ListElement{ name:"navigate_before"; value:"\ue408"}
    ListElement{ name:"navigate_next"; value:"\ue409"}
    ListElement{ name:"navigation"; value:"\ue55d"}
    ListElement{ name:"near_me"; value:"\ue569"}
    ListElement{ name:"network_cell"; value:"\ue1b9"}
    ListElement{ name:"network_check"; value:"\ue640"}
    ListElement{ name:"network_locked"; value:"\ue61a"}
    ListElement{ name:"network_wifi"; value:"\ue1ba"}
    ListElement{ name:"new_releases"; value:"\ue031"}
    ListElement{ name:"next_week"; value:"\ue16a"}
    ListElement{ name:"nfc"; value:"\ue1bb"}
    ListElement{ name:"no_encryption"; value:"\ue641"}
    ListElement{ name:"no_sim"; value:"\ue0cc"}
    ListElement{ name:"not_interested"; value:"\ue033"}
    ListElement{ name:"note"; value:"\ue06f"}
    ListElement{ name:"note_add"; value:"\ue89c"}
    ListElement{ name:"notifications"; value:"\ue7f4"}
    ListElement{ name:"notifications_active"; value:"\ue7f7"}
    ListElement{ name:"notifications_none"; value:"\ue7f5"}
    ListElement{ name:"notifications_off"; value:"\ue7f6"}
    ListElement{ name:"notifications_paused"; value:"\ue7f8"}
    ListElement{ name:"offline_pin"; value:"\ue90a"}
    ListElement{ name:"ondemand_video"; value:"\ue63a"}
    ListElement{ name:"opacity"; value:"\ue91c"}
    ListElement{ name:"open_in_browser"; value:"\ue89d"}
    ListElement{ name:"open_in_new"; value:"\ue89e"}
    ListElement{ name:"open_with"; value:"\ue89f"}
    ListElement{ name:"pages"; value:"\ue7f9"}
    ListElement{ name:"pageview"; value:"\ue8a0"}
    ListElement{ name:"palette"; value:"\ue40a"}
    ListElement{ name:"pan_tool"; value:"\ue925"}
    ListElement{ name:"panorama"; value:"\ue40b"}
    ListElement{ name:"panorama_fish_eye"; value:"\ue40c"}
    ListElement{ name:"panorama_horizontal"; value:"\ue40d"}
    ListElement{ name:"panorama_vertical"; value:"\ue40e"}
    ListElement{ name:"panorama_wide_angle"; value:"\ue40f"}
    ListElement{ name:"party_mode"; value:"\ue7fa"}
    ListElement{ name:"pause"; value:"\ue034"}
    ListElement{ name:"pause_circle_filled"; value:"\ue035"}
    ListElement{ name:"pause_circle_outline"; value:"\ue036"}
    ListElement{ name:"payment"; value:"\ue8a1"}
    ListElement{ name:"people"; value:"\ue7fb"}
    ListElement{ name:"people_outline"; value:"\ue7fc"}
    ListElement{ name:"perm_camera_mic"; value:"\ue8a2"}
    ListElement{ name:"perm_contact_calendar"; value:"\ue8a3"}
    ListElement{ name:"perm_data_setting"; value:"\ue8a4"}
    ListElement{ name:"perm_device_information"; value:"\ue8a5"}
    ListElement{ name:"perm_identity"; value:"\ue8a6"}
    ListElement{ name:"perm_media"; value:"\ue8a7"}
    ListElement{ name:"perm_phone_msg"; value:"\ue8a8"}
    ListElement{ name:"perm_scan_wifi"; value:"\ue8a9"}
    ListElement{ name:"person"; value:"\ue7fd"}
    ListElement{ name:"person_add"; value:"\ue7fe"}
    ListElement{ name:"person_outline"; value:"\ue7ff"}
    ListElement{ name:"person_pin"; value:"\ue55a"}
    ListElement{ name:"person_pin_circle"; value:"\ue56a"}
    ListElement{ name:"personal_video"; value:"\ue63b"}
    ListElement{ name:"pets"; value:"\ue91d"}
    ListElement{ name:"phone"; value:"\ue0cd"}
    ListElement{ name:"phone_android"; value:"\ue324"}
    ListElement{ name:"phone_bluetooth_speaker"; value:"\ue61b"}
    ListElement{ name:"phone_forwarded"; value:"\ue61c"}
    ListElement{ name:"phone_in_talk"; value:"\ue61d"}
    ListElement{ name:"phone_iphone"; value:"\ue325"}
    ListElement{ name:"phone_locked"; value:"\ue61e"}
    ListElement{ name:"phone_missed"; value:"\ue61f"}
    ListElement{ name:"phone_paused"; value:"\ue620"}
    ListElement{ name:"phonelink"; value:"\ue326"}
    ListElement{ name:"phonelink_erase"; value:"\ue0db"}
    ListElement{ name:"phonelink_lock"; value:"\ue0dc"}
    ListElement{ name:"phonelink_off"; value:"\ue327"}
    ListElement{ name:"phonelink_ring"; value:"\ue0dd"}
    ListElement{ name:"phonelink_setup"; value:"\ue0de"}
    ListElement{ name:"photo"; value:"\ue410"}
    ListElement{ name:"photo_album"; value:"\ue411"}
    ListElement{ name:"photo_camera"; value:"\ue412"}
    ListElement{ name:"photo_filter"; value:"\ue43b"}
    ListElement{ name:"photo_library"; value:"\ue413"}
    ListElement{ name:"photo_size_select_actual"; value:"\ue432"}
    ListElement{ name:"photo_size_select_large"; value:"\ue433"}
    ListElement{ name:"photo_size_select_small"; value:"\ue434"}
    ListElement{ name:"picture_as_pdf"; value:"\ue415"}
    ListElement{ name:"picture_in_picture"; value:"\ue8aa"}
    ListElement{ name:"picture_in_picture_alt"; value:"\ue911"}
    ListElement{ name:"pie_chart"; value:"\ue6c4"}
    ListElement{ name:"pie_chart_outlined"; value:"\ue6c5"}
    ListElement{ name:"pin_drop"; value:"\ue55e"}
    ListElement{ name:"place"; value:"\ue55f"}
    ListElement{ name:"play_arrow"; value:"\ue037"}
    ListElement{ name:"play_circle_filled"; value:"\ue038"}
    ListElement{ name:"play_circle_outline"; value:"\ue039"}
    ListElement{ name:"play_for_work"; value:"\ue906"}
    ListElement{ name:"playlist_add"; value:"\ue03b"}
    ListElement{ name:"playlist_add_check"; value:"\ue065"}
    ListElement{ name:"playlist_play"; value:"\ue05f"}
    ListElement{ name:"plus_one"; value:"\ue800"}
    ListElement{ name:"poll"; value:"\ue801"}
    ListElement{ name:"polymer"; value:"\ue8ab"}
    ListElement{ name:"pool"; value:"\ueb48"}
    ListElement{ name:"portable_wifi_off"; value:"\ue0ce"}
    ListElement{ name:"portrait"; value:"\ue416"}
    ListElement{ name:"power"; value:"\ue63c"}
    ListElement{ name:"power_input"; value:"\ue336"}
    ListElement{ name:"power_settings_new"; value:"\ue8ac"}
    ListElement{ name:"pregnant_woman"; value:"\ue91e"}
    ListElement{ name:"present_to_all"; value:"\ue0df"}
    ListElement{ name:"iconprint"; value:"\ue8ad"}
    ListElement{ name:"priority_high"; value:"\ue645"}
    ListElement{ name:"iconpublic"; value:"\ue80b"}
    ListElement{ name:"publish"; value:"\ue255"}
    ListElement{ name:"query_builder"; value:"\ue8ae"}
    ListElement{ name:"question_answer"; value:"\ue8af"}
    ListElement{ name:"queue"; value:"\ue03c"}
    ListElement{ name:"queue_music"; value:"\ue03d"}
    ListElement{ name:"queue_play_next"; value:"\ue066"}
    ListElement{ name:"radio"; value:"\ue03e"}
    ListElement{ name:"radio_button_checked"; value:"\ue837"}
    ListElement{ name:"radio_button_unchecked"; value:"\ue836"}
    ListElement{ name:"rate_review"; value:"\ue560"}
    ListElement{ name:"receipt"; value:"\ue8b0"}
    ListElement{ name:"recent_actors"; value:"\ue03f"}
    ListElement{ name:"record_voice_over"; value:"\ue91f"}
    ListElement{ name:"redeem"; value:"\ue8b1"}
    ListElement{ name:"redo"; value:"\ue15a"}
    ListElement{ name:"refresh"; value:"\ue5d5"}
    ListElement{ name:"remove"; value:"\ue15b"}
    ListElement{ name:"remove_circle"; value:"\ue15c"}
    ListElement{ name:"remove_circle_outline"; value:"\ue15d"}
    ListElement{ name:"remove_from_queue"; value:"\ue067"}
    ListElement{ name:"remove_red_eye"; value:"\ue417"}
    ListElement{ name:"remove_shopping_cart"; value:"\ue928"}
    ListElement{ name:"reorder"; value:"\ue8fe"}
    ListElement{ name:"repeat"; value:"\ue040"}
    ListElement{ name:"repeat_one"; value:"\ue041"}
    ListElement{ name:"replay"; value:"\ue042"}
    ListElement{ name:"replay_10"; value:"\ue059"}
    ListElement{ name:"replay_30"; value:"\ue05a"}
    ListElement{ name:"replay_5"; value:"\ue05b"}
    ListElement{ name:"reply"; value:"\ue15e"}
    ListElement{ name:"reply_all"; value:"\ue15f"}
    ListElement{ name:"report"; value:"\ue160"}
    ListElement{ name:"report_problem"; value:"\ue8b2"}
    ListElement{ name:"restaurant"; value:"\ue56c"}
    ListElement{ name:"restaurant_menu"; value:"\ue561"}
    ListElement{ name:"restore"; value:"\ue8b3"}
    ListElement{ name:"restore_page"; value:"\ue929"}
    ListElement{ name:"ring_volume"; value:"\ue0d1"}
    ListElement{ name:"room"; value:"\ue8b4"}
    ListElement{ name:"room_service"; value:"\ueb49"}
    ListElement{ name:"rotate_90_degrees_ccw"; value:"\ue418"}
    ListElement{ name:"rotate_left"; value:"\ue419"}
    ListElement{ name:"rotate_right"; value:"\ue41a"}
    ListElement{ name:"rounded_corner"; value:"\ue920"}
    ListElement{ name:"router"; value:"\ue328"}
    ListElement{ name:"rowing"; value:"\ue921"}
    ListElement{ name:"rss_feed"; value:"\ue0e5"}
    ListElement{ name:"rv_hookup"; value:"\ue642"}
    ListElement{ name:"satellite"; value:"\ue562"}
    ListElement{ name:"save"; value:"\ue161"}
    ListElement{ name:"scanner"; value:"\ue329"}
    ListElement{ name:"schedule"; value:"\ue8b5"}
    ListElement{ name:"school"; value:"\ue80c"}
    ListElement{ name:"screen_lock_landscape"; value:"\ue1be"}
    ListElement{ name:"screen_lock_portrait"; value:"\ue1bf"}
    ListElement{ name:"screen_lock_rotation"; value:"\ue1c0"}
    ListElement{ name:"screen_rotation"; value:"\ue1c1"}
    ListElement{ name:"screen_share"; value:"\ue0e2"}
    ListElement{ name:"sd_card"; value:"\ue623"}
    ListElement{ name:"sd_storage"; value:"\ue1c2"}
    ListElement{ name:"search"; value:"\ue8b6"}
    ListElement{ name:"security"; value:"\ue32a"}
    ListElement{ name:"select_all"; value:"\ue162"}
    ListElement{ name:"send"; value:"\ue163"}
    ListElement{ name:"sentiment_dissatisfied"; value:"\ue811"}
    ListElement{ name:"sentiment_neutral"; value:"\ue812"}
    ListElement{ name:"sentiment_satisfied"; value:"\ue813"}
    ListElement{ name:"sentiment_very_dissatisfied"; value:"\ue814"}
    ListElement{ name:"sentiment_very_satisfied"; value:"\ue815"}
    ListElement{ name:"settings"; value:"\ue8b8"}
    ListElement{ name:"settings_applications"; value:"\ue8b9"}
    ListElement{ name:"settings_backup_restore"; value:"\ue8ba"}
    ListElement{ name:"settings_bluetooth"; value:"\ue8bb"}
    ListElement{ name:"settings_brightness"; value:"\ue8bd"}
    ListElement{ name:"settings_cell"; value:"\ue8bc"}
    ListElement{ name:"settings_ethernet"; value:"\ue8be"}
    ListElement{ name:"settings_input_antenna"; value:"\ue8bf"}
    ListElement{ name:"settings_input_component"; value:"\ue8c0"}
    ListElement{ name:"settings_input_composite"; value:"\ue8c1"}
    ListElement{ name:"settings_input_hdmi"; value:"\ue8c2"}
    ListElement{ name:"settings_input_svideo"; value:"\ue8c3"}
    ListElement{ name:"settings_overscan"; value:"\ue8c4"}
    ListElement{ name:"settings_phone"; value:"\ue8c5"}
    ListElement{ name:"settings_power"; value:"\ue8c6"}
    ListElement{ name:"settings_remote"; value:"\ue8c7"}
    ListElement{ name:"settings_system_daydream"; value:"\ue1c3"}
    ListElement{ name:"settings_voice"; value:"\ue8c8"}
    ListElement{ name:"share"; value:"\ue80d"}
    ListElement{ name:"shop"; value:"\ue8c9"}
    ListElement{ name:"shop_two"; value:"\ue8ca"}
    ListElement{ name:"shopping_basket"; value:"\ue8cb"}
    ListElement{ name:"shopping_cart"; value:"\ue8cc"}
    ListElement{ name:"short_text"; value:"\ue261"}
    ListElement{ name:"show_chart"; value:"\ue6e1"}
    ListElement{ name:"shuffle"; value:"\ue043"}
    ListElement{ name:"signal_cellular_4_bar"; value:"\ue1c8"}
    ListElement{ name:"signal_cellular_connected_no_internet_4_bar"; value:"\ue1cd"}
    ListElement{ name:"signal_cellular_no_sim"; value:"\ue1ce"}
    ListElement{ name:"signal_cellular_null"; value:"\ue1cf"}
    ListElement{ name:"signal_cellular_off"; value:"\ue1d0"}
    ListElement{ name:"signal_wifi_4_bar"; value:"\ue1d8"}
    ListElement{ name:"signal_wifi_4_bar_lock"; value:"\ue1d9"}
    ListElement{ name:"signal_wifi_off"; value:"\ue1da"}
    ListElement{ name:"sim_card"; value:"\ue32b"}
    ListElement{ name:"sim_card_alert"; value:"\ue624"}
    ListElement{ name:"skip_next"; value:"\ue044"}
    ListElement{ name:"skip_previous"; value:"\ue045"}
    ListElement{ name:"slideshow"; value:"\ue41b"}
    ListElement{ name:"slow_motion_video"; value:"\ue068"}
    ListElement{ name:"smartphone"; value:"\ue32c"}
    ListElement{ name:"smoke_free"; value:"\ueb4a"}
    ListElement{ name:"smoking_rooms"; value:"\ueb4b"}
    ListElement{ name:"sms"; value:"\ue625"}
    ListElement{ name:"sms_failed"; value:"\ue626"}
    ListElement{ name:"snooze"; value:"\ue046"}
    ListElement{ name:"sort"; value:"\ue164"}
    ListElement{ name:"sort_by_alpha"; value:"\ue053"}
    ListElement{ name:"spa"; value:"\ueb4c"}
    ListElement{ name:"space_bar"; value:"\ue256"}
    ListElement{ name:"speaker"; value:"\ue32d"}
    ListElement{ name:"speaker_group"; value:"\ue32e"}
    ListElement{ name:"speaker_notes"; value:"\ue8cd"}
    ListElement{ name:"speaker_notes_off"; value:"\ue92a"}
    ListElement{ name:"speaker_phone"; value:"\ue0d2"}
    ListElement{ name:"spellcheck"; value:"\ue8ce"}
    ListElement{ name:"star"; value:"\ue838"}
    ListElement{ name:"star_border"; value:"\ue83a"}
    ListElement{ name:"star_half"; value:"\ue839"}
    ListElement{ name:"stars"; value:"\ue8d0"}
    ListElement{ name:"stay_current_landscape"; value:"\ue0d3"}
    ListElement{ name:"stay_current_portrait"; value:"\ue0d4"}
    ListElement{ name:"stay_primary_landscape"; value:"\ue0d5"}
    ListElement{ name:"stay_primary_portrait"; value:"\ue0d6"}
    ListElement{ name:"stop"; value:"\ue047"}
    ListElement{ name:"stop_screen_share"; value:"\ue0e3"}
    ListElement{ name:"storage"; value:"\ue1db"}
    ListElement{ name:"store"; value:"\ue8d1"}
    ListElement{ name:"store_mall_directory"; value:"\ue563"}
    ListElement{ name:"straighten"; value:"\ue41c"}
    ListElement{ name:"streetview"; value:"\ue56e"}
    ListElement{ name:"strikethrough_s"; value:"\ue257"}
    ListElement{ name:"style"; value:"\ue41d"}
    ListElement{ name:"subdirectory_arrow_left"; value:"\ue5d9"}
    ListElement{ name:"subdirectory_arrow_right"; value:"\ue5da"}
    ListElement{ name:"subject"; value:"\ue8d2"}
    ListElement{ name:"subscriptions"; value:"\ue064"}
    ListElement{ name:"subtitles"; value:"\ue048"}
    ListElement{ name:"subway"; value:"\ue56f"}
    ListElement{ name:"supervisor_account"; value:"\ue8d3"}
    ListElement{ name:"surround_sound"; value:"\ue049"}
    ListElement{ name:"swap_calls"; value:"\ue0d7"}
    ListElement{ name:"swap_horiz"; value:"\ue8d4"}
    ListElement{ name:"swap_vert"; value:"\ue8d5"}
    ListElement{ name:"swap_vertical_circle"; value:"\ue8d6"}
    ListElement{ name:"switch_camera"; value:"\ue41e"}
    ListElement{ name:"switch_video"; value:"\ue41f"}
    ListElement{ name:"sync"; value:"\ue627"}
    ListElement{ name:"sync_disabled"; value:"\ue628"}
    ListElement{ name:"sync_problem"; value:"\ue629"}
    ListElement{ name:"system_update"; value:"\ue62a"}
    ListElement{ name:"system_update_alt"; value:"\ue8d7"}
    ListElement{ name:"tab"; value:"\ue8d8"}
    ListElement{ name:"tab_unselected"; value:"\ue8d9"}
    ListElement{ name:"tablet"; value:"\ue32f"}
    ListElement{ name:"tablet_android"; value:"\ue330"}
    ListElement{ name:"tablet_mac"; value:"\ue331"}
    ListElement{ name:"tag_faces"; value:"\ue420"}
    ListElement{ name:"tap_and_play"; value:"\ue62b"}
    ListElement{ name:"terrain"; value:"\ue564"}
    ListElement{ name:"text_fields"; value:"\ue262"}
    ListElement{ name:"text_format"; value:"\ue165"}
    ListElement{ name:"textsms"; value:"\ue0d8"}
    ListElement{ name:"texture"; value:"\ue421"}
    ListElement{ name:"theaters"; value:"\ue8da"}
    ListElement{ name:"thumb_down"; value:"\ue8db"}
    ListElement{ name:"thumb_up"; value:"\ue8dc"}
    ListElement{ name:"thumbs_up_down"; value:"\ue8dd"}
    ListElement{ name:"time_to_leave"; value:"\ue62c"}
    ListElement{ name:"timelapse"; value:"\ue422"}
    ListElement{ name:"timeline"; value:"\ue922"}
    ListElement{ name:"timer"; value:"\ue425"}
    ListElement{ name:"timer_10"; value:"\ue423"}
    ListElement{ name:"timer_3"; value:"\ue424"}
    ListElement{ name:"timer_off"; value:"\ue426"}
    ListElement{ name:"title"; value:"\ue264"}
    ListElement{ name:"toc"; value:"\ue8de"}
    ListElement{ name:"today"; value:"\ue8df"}
    ListElement{ name:"toll"; value:"\ue8e0"}
    ListElement{ name:"tonality"; value:"\ue427"}
    ListElement{ name:"touch_app"; value:"\ue913"}
    ListElement{ name:"toys"; value:"\ue332"}
    ListElement{ name:"track_changes"; value:"\ue8e1"}
    ListElement{ name:"traffic"; value:"\ue565"}
    ListElement{ name:"train"; value:"\ue570"}
    ListElement{ name:"tram"; value:"\ue571"}
    ListElement{ name:"transfer_within_a_station"; value:"\ue572"}
    ListElement{ name:"transform"; value:"\ue428"}
    ListElement{ name:"translate"; value:"\ue8e2"}
    ListElement{ name:"trending_down"; value:"\ue8e3"}
    ListElement{ name:"trending_flat"; value:"\ue8e4"}
    ListElement{ name:"trending_up"; value:"\ue8e5"}
    ListElement{ name:"tune"; value:"\ue429"}
    ListElement{ name:"turned_in"; value:"\ue8e6"}
    ListElement{ name:"turned_in_not"; value:"\ue8e7"}
    ListElement{ name:"tv"; value:"\ue333"}
    ListElement{ name:"unarchive"; value:"\ue169"}
    ListElement{ name:"undo"; value:"\ue166"}
    ListElement{ name:"unfold_less"; value:"\ue5d6"}
    ListElement{ name:"unfold_more"; value:"\ue5d7"}
    ListElement{ name:"update"; value:"\ue923"}
    ListElement{ name:"usb"; value:"\ue1e0"}
    ListElement{ name:"verified_user"; value:"\ue8e8"}
    ListElement{ name:"vertical_align_bottom"; value:"\ue258"}
    ListElement{ name:"vertical_align_center"; value:"\ue259"}
    ListElement{ name:"vertical_align_top"; value:"\ue25a"}
    ListElement{ name:"vibration"; value:"\ue62d"}
    ListElement{ name:"video_call"; value:"\ue070"}
    ListElement{ name:"video_label"; value:"\ue071"}
    ListElement{ name:"video_library"; value:"\ue04a"}
    ListElement{ name:"videocam"; value:"\ue04b"}
    ListElement{ name:"videocam_off"; value:"\ue04c"}
    ListElement{ name:"videogame_asset"; value:"\ue338"}
    ListElement{ name:"view_agenda"; value:"\ue8e9"}
    ListElement{ name:"view_array"; value:"\ue8ea"}
    ListElement{ name:"view_carousel"; value:"\ue8eb"}
    ListElement{ name:"view_column"; value:"\ue8ec"}
    ListElement{ name:"view_comfy"; value:"\ue42a"}
    ListElement{ name:"view_compact"; value:"\ue42b"}
    ListElement{ name:"view_day"; value:"\ue8ed"}
    ListElement{ name:"view_headline"; value:"\ue8ee"}
    ListElement{ name:"view_list"; value:"\ue8ef"}
    ListElement{ name:"view_module"; value:"\ue8f0"}
    ListElement{ name:"view_quilt"; value:"\ue8f1"}
    ListElement{ name:"view_stream"; value:"\ue8f2"}
    ListElement{ name:"view_week"; value:"\ue8f3"}
    ListElement{ name:"vignette"; value:"\ue435"}
    ListElement{ name:"visibility"; value:"\ue8f4"}
    ListElement{ name:"visibility_off"; value:"\ue8f5"}
    ListElement{ name:"voice_chat"; value:"\ue62e"}
    ListElement{ name:"voicemail"; value:"\ue0d9"}
    ListElement{ name:"volume_down"; value:"\ue04d"}
    ListElement{ name:"volume_mute"; value:"\ue04e"}
    ListElement{ name:"volume_off"; value:"\ue04f"}
    ListElement{ name:"volume_up"; value:"\ue050"}
    ListElement{ name:"vpn_key"; value:"\ue0da"}
    ListElement{ name:"vpn_lock"; value:"\ue62f"}
    ListElement{ name:"wallpaper"; value:"\ue1bc"}
    ListElement{ name:"warning"; value:"\ue002"}
    ListElement{ name:"watch"; value:"\ue334"}
    ListElement{ name:"watch_later"; value:"\ue924"}
    ListElement{ name:"wb_auto"; value:"\ue42c"}
    ListElement{ name:"wb_cloudy"; value:"\ue42d"}
    ListElement{ name:"wb_incandescent"; value:"\ue42e"}
    ListElement{ name:"wb_iridescent"; value:"\ue436"}
    ListElement{ name:"wb_sunny"; value:"\ue430"}
    ListElement{ name:"wc"; value:"\ue63d"}
    ListElement{ name:"web"; value:"\ue051"}
    ListElement{ name:"web_asset"; value:"\ue069"}
    ListElement{ name:"weekend"; value:"\ue16b"}
    ListElement{ name:"whatshot"; value:"\ue80e"}
    ListElement{ name:"widgets"; value:"\ue1bd"}
    ListElement{ name:"wifi"; value:"\ue63e"}
    ListElement{ name:"wifi_lock"; value:"\ue1e1"}
    ListElement{ name:"wifi_tethering"; value:"\ue1e2"}
    ListElement{ name:"work"; value:"\ue8f9"}
    ListElement{ name:"wrap_text"; value:"\ue25b"}
    ListElement{ name:"youtube_searched_for"; value:"\ue8fa"}
    ListElement{ name:"zoom_in"; value:"\ue8ff"}
    ListElement{ name:"zoom_out"; value:"\ue900"}
    ListElement{ name:"zoom_out_map"; value:"\ue56b"}
    

}
